name: swagger
version: 1.0.0
description: Swagger API Client
dependencies:
  http: '>=0.11.1 <0.12.0'
  dartson: "^0.2.4"
  swagger:
    git: https://github.com/switchdatabase/Switch-API-Dart-Client.git
      version: 'any'

dev_dependencies:
  guinness: '^0.1.17'
  browser: any

transformers:
  - dartson
